version: '3.1'
services:
  web:
    image: frojd/company_project_web
    build: ./src
    volumes:
      - "./src:/app:cached"
      - "./docker/files/shared:/shared:rw"
      - "./docker/files/var/log:/var/log:rw"
      - "./docker/files/certs:/priv/cert:cached"
    ports:
      - "8081:8000"
      - "5678:5678"
    depends_on:
      - db
    env_file: ./docker/config/web.env
  ssr:
    image: frojd/hypernova
    build:
      context: ./hypernova
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app:cached"
      - ".ignored-node_modules:/app/node_modules"
    ports:
      - "3030:3000"
    environment:
      - HYPERNOVA_PORT=3000
  db:
    image: mdillon/postgis:10
    ports:
      - "8082:5432"
    volumes:
      - "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/:cached"
      - "./docker/files/shared:/shared:rw"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
